version: '3.4'

services:
    plc:
        container_name: fcplc
        build:
            context: .
            dockerfile: Dockerfile
        privileged: true
        restart: always
        network_mode: bridge
        ports:
            - "8080:8080"
        environment:
            FTEST: ${FTEST}
        volumes:
          - /dev/mem:/dev/mem
          - /proc/cpuinfo:/proc/cpuinfo
          - /sys/bus/w1/devices/:/sys/bus/w1/devices/
          - ./data:/usr/src/app/data/